spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true